import Head from "next/head";

import { LP } from "../components/Page/LP";
import { APP_NAME } from "../constants/Consts/App";

import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>{APP_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <LP />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
